// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKU-dZ-b9hI0S-4WnwgX6_ltUkxbNlI4',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'cointrue-demo-project',
    authDomain: 'cointrue-demo-project.firebaseapp.com',
    storageBucket: 'cointrue-demo-project.appspot.com',
    measurementId: 'G-9JSY05YM9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvKU-dZ-b9hI0S-4WnwgX6_ltUkxbNlI4',
    appId: '1:448618578101:android:73a4fb8297b2cd93ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'cointrue-demo-project',
    storageBucket: 'cointrue-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKU-dZ-b9hI0S-4WnwgX6_ltUkxbNlI4',
    appId: '1:448618578101:ios:73a4fb8297b2cd93ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'cointrue-demo-project',
    storageBucket: 'cointrue-demo-project.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKU-dZ-b9hI0S-4WnwgX6_ltUkxbNlI4',
    appId: '1:448618578101:macos:73a4fb8297b2cd93ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'cointrue-demo-project',
    storageBucket: 'cointrue-demo-project.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKU-dZ-b9hI0S-4WnwgX6_ltUkxbNlI4',
    appId: '1:448618578101:windows:73a4fb8297b2cd93ac3efc',
    messagingSenderId: '448618578101',
    projectId: 'cointrue-demo-project',
    storageBucket: 'cointrue-demo-project.appspot.com',
  );
}
